
CXX=g++

# If the .env file exists include it, no warnings will be generated if it does not exist (-include vs include)
-include ./env

# Directory for the binary
BIN_DIR := ./bin
# The final binary target to produce
TARGET := ${BIN_DIR}/ssmbo_emo2025.exe

# ------------

# Set the language standards to use
CFLAGS = -std=c17
CXXFLAGS = -std=c++17

# Define a variable to track flags that are common to C and CXX compilers
C_CXX_FLAGS = 

# Control optimisation level / build configuration.
# ----------------------
# Config: Release builds:
C_CXX_FLAGS += -O3

# Config: RelWithDebInfo
# C_CXX_FLAGS += -O3 -g

# Config: Profile (for gprof)
# C_CXX_FLAGS += -O3 -pg 

# Config: Unoptimised
# C_CXX_FLAGS += -O0

# Config: Debug
# C_CXX_FLAGS +=  -O0 -g
# ----------------------

# Enable a high level of warnings
C_CXX_FLAGS += -Wall -Wextra -Wuninitialized -Wmaybe-uninitialized
# Suppress some unwatned warnings
C_CXX_FLAGS += -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable
# Optionally promote warnigns to errors. This can make development more painful but enforces no warnings
# C_CXX_FLAGS += -Werror

# Add include dependency generation, for simpler makefiles (with a slight compiler time increase)
C_CXX_FLAGS += -MD

# ------------

# Define commonly used directories
INC_DIR := ./include
SRC_DIR := ./src
OBJ_DIR := ./objects

# Build a list of .o files to compile, by finding .cpp files in known directories.
SRC_DIRS := $(SRC_DIR)
INC_DIRS := $(INC_DIR)

# Find all source files in the source directories
SRC_FILES := $(foreach dir,$(SRC_DIRS),$(wildcard $(addprefix $(dir)/*,.cpp)))
# Discard .template.cpp files if any were found.
SRC_FILES := $(filter-out %.template.cpp,$(SRC_FILES))
# Discard any directories from the above, to support ../
# This would allow name collisions where core and mega_model contain source files with the same name.
SRC_FILES := $(notdir ${SRC_FILES})
# Build the list of .o files to build and link into the final binary
OBJS := $(addprefix ${OBJ_DIR}/,$(addsuffix .o,$(basename $(SRC_FILES))))

# Build the list of include flags from the listed include directories + boost
INCLUDE = $(foreach dir,$(INC_DIRS),-I$(dir)) $(BOOST_INCLUDE) $(TIGON_INCLUDE)

# From the list of objects build the list of dependency files created via -MD
DEPENDS=$(OBJS:.o=.d)

# Variables used to control how C/CXX files are compiled, or how binaries are linked
COMPILE_C = $(CXX) $(CFLAGS) $(C_CXX_FLAGS) $(INCLUDE)
COMPILE_CXX = $(CXX) $(CXXFLAGS) $(C_CXX_FLAGS) $(INCLUDE)
LINK_CXX = $(CXX) $(CXXFLAGS) $(C_CXX_FLAGS) $(BOOST_LIB_DIR) $(TIGON_LIB_DIR)

# ------------

# Clear default .SUFFIXES rules
.SUFFIXES:

# List targets which do not directly create files with the same name as the target
.PHONY: all clean clean_data createfolders compile 

# Default / all rule
all: createfolders compile

# Rule for debugging makefile variabels, use make echo-<VAR>
echo-%: ; @echo $*=$($*)

# Clean files generated by the compitation process
clean:
	rm -f $(BIN_DIR)/*
	rm -f $(OBJ_DIR)/*.o
	rm -fr $(OBJ_DIR)
	rm -fr $(BIN_DIR)

# Clean data files generated by running the binary
clean_data:
	rm -f *.csv
	rm -f ./outputs/*.csv
	rm -f ./outputs/*.txt
	rm -f ./logs/*.*
	rm -fr outputs

# Create required directories
createfolders:
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(BIN_DIR)
	@mkdir -p outputs

# Generic compilation rule, depends on directories and the final binary
compile: createfolders $(TARGET)

# Include the generated .d files for rule inclusion
-include $(DEPENDS)

# Rule for compiling a C++ file into an object file
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(COMPILE_CXX) -c $< -o $@

# Rule for linking the final executable from a list of objects.
$(TARGET): $(OBJS)
	$(LINK_CXX) $^ -o $@ $(BOOST_LIBS) $(TIGON_LIBS) $(LDFLAGS)
